### ISSUE TITLE
Share story pop-up screen ( see image) should display the next flower pack rather than the color

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#106]
![image](https://user-images.githubusercontent.com/46975347/54700140-c648eb80-4b08-11e9-90ca-9c88496397dd.png)

this screen should look like this instead:
![image](https://user-images.githubusercontent.com/46975347/54700215-f5f7f380-4b08-11e9-9d4b-656fac855c33.png)

**Comment by hermansaksono** [comment]
@xinylin360, what if the user has unlocked all of the flower packs. Show we just show nothing?

**Comment by hermansaksono** [comment]
Addressed in PR 52
