### ISSUE TITLE
updates on nursery page (see image:  changes are in red)

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#119]
![image](https://user-images.githubusercontent.com/46975347/54717374-682eff00-4b2e-11e9-9eab-2526607fec6e.png)

**Comment by hermansaksono** [comment]
Hi @xinylin360, this is the proposed changes in the Nursery view. Let me know what you think.

![layout-2019-03-26-140539](https://user-images.githubusercontent.com/9420115/55022261-926e3a00-4fd0-11e9-8589-4f010edd7c06.png)

**Comment by hermansaksono** [comment]
Changes includes:
- show the daily step goal for the week on nursery page (#113)
- In "weekly progress", it should show the user's daily step goal this week. (#109)

**Comment by hermansaksono** [comment]
@takyyon please check `feature/nursery_redesign` branch

**Comment by hermansaksono** [comment]
Addressed in PR 54
