### ISSUE TITLE
when averaging steps for the previous week for the new goal, don't count "0" in the average

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#137]
so if the user has 6 days of 0 steps and 1 day that is 3000 steps, the average should only count 3000 steps as the average. 

if user has 5 days of 0 steps and 1 day of 1000 and 1 day of 2000, the average should be (1000+2000)/2, rather than dividing it by 7.

**Comment by hermansaksono** [comment]
Note: This is handled by the server

**Comment by hermansaksono** [comment]
I'm closing this issue. Please check whether the issue persists to happen.
