### ISSUE TITLE
Notification System Needed 

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#17]

**Comment by estowell** [comment]
- when flower is ready to grow (i.e., finished with step goal)
- when user received a message (someone liked it or commented on it)?
- remind users to use app after a few days
- 

Google Doc listing notifications needed
https://docs.google.com/document/d/1UpfVs-vEiCbxZWtsXK-Jhv8ILHOWAsjq0qTP3bjDhj0/edit

**Comment by hermansaksono** [comment]
@estowell @xinylin360 I'm proposing this schedule for the notifications. Let me know what you think:
* when flower is ready to grow (i.e., finished with step goal) -> in the morning after the 7-day challenge is completed
* when user received a message (someone liked it or commented on it)? -> on demand
* remind users to use app after a few days -> every day at 6pm check if last login time > 48 hours, if yes send notification

What do you think?

**Comment by xinylin360** [comment]
yes that works for me! How about when they haven't logged their exercise for a while?
