### ISSUE TITLE
Profile page is needed

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#18]
- Placement/development of profile, help/FAQ page (Xin & Connor)
- Put on the right side of “My Garden”
- Design for Profile Page (see below) (Xin & Connor)
- Drop down menu
- Information to include in the profile (Xin & Connor)
- Profile Icons and colors - designs (Xin)
- Small files!
- The ability to change and customize icons

**Comment by estowell** [comment]
@xinylin360 : create designs showing where the profile page will be accessed and where information from the profile page will be used in the app

**Comment by hermansaksono** [comment]
@xinylin360 @estowell this is the design of the profile page that I have implemented in Android.

![profile_page](https://user-images.githubusercontent.com/9420115/52744830-b25f1680-2fab-11e9-8d4d-b52108aa177b.png)

The profile page can be accessed by tapping on the profile iconin My Garden:

![my_garden_with_profile](https://user-images.githubusercontent.com/9420115/52744952-efc3a400-2fab-11e9-8a6d-6935184fc5ad.png)

Also, @takyyon, these designs can be accessed from `features/profile_page`.

**Comment by hermansaksono** [comment]
@takyyon can you make the "caregiving for my %PATIENT_RELATIONSHIP%" dynamic by taking the value stored in Firebase? Maybe under `user_setting`?

We don't need to provide an interface for the user to enter their relationship because this will be done by the research staff through the backend.
