### ISSUE TITLE
Need clarifications for "multiplying flower and stories"

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#27]
How to make this obvious? (Xin)
Have a page that pops out when they get the multiplied flowers, letting them know how many flowers they got. Example here:

**Comment by xinylin360** [comment]
I was thinking of something like "multiple the flower by logging more exercise! And there will be options to log exercise. Like the picture here

<img width="204" alt="multiply flowers" src="https://user-images.githubusercontent.com/46975347/51999778-8448e500-2489-11e9-83df-db6700ce30d7.PNG">

**Comment by hermansaksono** [comment]
I have simplified the screen for logging exercise, but the codes are still in my local development branch because our Github is down.

To save time, I propose that the explanation about how Exercise Logs works should be given verbally in person, rather using the app to explain this feature.

What do you think @xinylin360 @estowell @andreagparker? Please let me know if we can go ahead with this design and I will close this issue.

**Comment by xinylin360** [comment]
Can I take a look at the design first?

**Comment by hermansaksono** [comment]
@xinylin360 Sure. This is the redesigned screen for reviewing exercise log:

![screenshot_20190220-181653](https://user-images.githubusercontent.com/9420115/53131948-39783580-353c-11e9-9340-6037ca0cd288.png)

This is the list of exercise group. Nothing changed:
![screenshot_20190220-181657](https://user-images.githubusercontent.com/9420115/53132013-5d3b7b80-353c-11e9-9601-42686a63a47c.png)

This is the list of exercises to do with the new log exercise button:
![screenshot_20190220-181701](https://user-images.githubusercontent.com/9420115/53132033-69273d80-353c-11e9-957b-c91796bc1605.png)

This is the confirmation dialog when a user tapped the log exercise button. This is to prevent users from loggin exercises by accident:
![screenshot_20190220-181706](https://user-images.githubusercontent.com/9420115/53132061-83611b80-353c-11e9-812b-d89908763b5d.png)

**Comment by xinylin360** [comment]
This looks good to me!!
