### ISSUE TITLE
Need to show the 7 days of the challenge

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#30]

**Comment by estowell** [comment]
In the challenge screen - 
The flower should show the weekly progress, but the bar below shows the daily step progress. How can we make this clear? Does it require a different label? 
@xinylin360 @breenmackenzie15

**Comment by xinylin360** [comment]
I think it's better if we just have a label on top that says something like day 1, day 2, etc like the screenshot below, or we can day 1 of week 1, day 2 of week 1, etc.

<img width="162" alt="day 2" src="https://user-images.githubusercontent.com/46975347/52000677-af343880-248b-11e9-9459-6e844664e164.PNG">

**Comment by estowell** [comment]
@xinylin360 Can we update this design? Right now, exercise, stories, and the flower reflect the week's progress while the steps reflect only the progress that day. 

Idea - 
This week's progress (at the top)
Challenge Day 1 :

**Comment by hermansaksono** [comment]
I've redesigned this page like this. What do you think @xinylin360 @estowell?

I'm closing this issue, but we can always reopen it.

![screenshot_20190215-194908](https://user-images.githubusercontent.com/9420115/52891742-f17f9a00-315a-11e9-8cf7-192eac3ed3cb.png)

**Comment by hermansaksono** [comment]
I'm closing this issue, but we can always reopen it.
