### ISSUE TITLE
Warning to users that everyone can view a story prior to posting

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#48]

**Comment by hermansaksono** [comment]
Have a text on top of the text box.
@xinylin360 will prepare the wording.

**Comment by xinylin360** [comment]
Right now the text says "Write a story!" Instead we can say something like "Write a story that you will feel comfortable sharing with everyone. Click here to choose a story prompt, or write your own!"

**Comment by hermansaksono** [comment]
I put an informational text in the story sharing screen.
![screen shot 2019-02-12 at 7 27 23 pm](https://user-images.githubusercontent.com/9420115/52677553-4ffb0d00-2efc-11e9-9f0c-9e676e4a6296.png)

**Comment by xinylin360** [comment]
looks good to me!
