### ISSUE TITLE
No feedback or confirmation after logging an exercise.

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#5]
1. Go to the Exercise page, then go to Tutorials.
2. Tap one of the plus (+) buttons

Results: No feedback that exercise was logged. No confirmation whether the user really wanted to log an exercise.

Suggestion: Add a confirmation dialog ("Do you want to log one exercise?"), then switch to the Logs screen.

**Comment by estowell** [comment]
add button - pop up and click "ok"

**Comment by hermansaksono** [comment]
In my development branch, tapping the add button will show a confirmation dialog that asks "Do you want to log this exercise?". If the user tapped "Yes", one exercise will be logged. Then a Toast that says "Exercise has been logged" will confirm this. If the user tapped "No", then nothing is going to happen.
