### ISSUE TITLE
Log users' activity

### ISSUE THREAD

**Issue by estowell** [WellnessLab/adc_caregiver#54]

**Comment by andreagparker** [comment]
I think this is with respect to our need to log user actions within the game so that we can analyze them as part of the study. I'm not sure if any logging has been implemented yet?

**Comment by hermansaksono** [comment]
We can definitely use the API that Raj developed last year:

https://github.com/WellnessLab/user_logging

If this is the direction we're going. We need to do two things. First, define the events that we want to log. Then add the logging codes on the relevant events in the app. The log data will be in JSON format and can be processed and analyzed using Python.

[wellness-storytelling-user_logging-export.json.zip](https://github.com/WellnessLab/adc_caregiver/files/2792418/wellness-storytelling-user_logging-export.json.zip)

**Comment by hermansaksono** [comment]
Possible events:
- APP_OPEN
- VISIT_OTHER_GARDEN
- LOG_EXERCISE
- REFRESH_STEPS
- START_CHALLENGE

@xinylin360 will develop the list of events

**Comment by estowell** [comment]
Google Doc of Logging:
https://docs.google.com/document/d/1UpfVs-vEiCbxZWtsXK-Jhv8ILHOWAsjq0qTP3bjDhj0/edit

**Comment by hermansaksono** [comment]
`      
        WellnessUserLogging userLogging = new WellnessUserLogging(groupName);
        Bundle bundle = new Bundle();
        bundle.putString("STORY_ID", this.story.getId());
        userLogging.logEvent("READ_STORY", bundle);`
