### ISSUE TITLE
Game stops working after all the challenges are done

### ISSUE THREAD

**Issue by estowell** [WellnessLab/adc_caregiver#56]

**Comment by hermansaksono** [comment]
Tentative: the app will crash if there's no more level available. @xinylin360 will investigate how to reproduce this bug.

**Comment by hermansaksono** [comment]
Hi @xinylin360, I have added 2 more levels. Let me know if this bug is still occurring.

**Comment by hermansaksono** [comment]
This is identincal to this: https://github.com/WellnessLab/adc_caregiver/issues/55
