### ISSUE TITLE
Need icons for profile pictures

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#69]
Hi @xinylin360, Krrish has completed the feature to pick profile picture icon. I know you have made several profile pictures. Do you think you can provide the profile icons in these configurations when exporting from AI to SVG:

- Canvas size: 512 x 512 px
- An icon should be centered on the canvas (x=256px, y=256px)
- An icon should have the same width and height (w=512px, h=512px).

Below is an icon that follows the above configuration:
![profile_pic_01](https://user-images.githubusercontent.com/9420115/53366100-d4905700-3910-11e9-9645-dfc69f029e12.png)

Once you have the nine SVG files ready, please send it to @takyyon (Krrish) so he can put it into the Android app.

**Comment by xinylin360** [comment]
I just sent it to Krish and uploaded to google drive 
https://drive.google.com/drive/u/2/folders/15JBk6u-GtgJCd7QW9QPDtzEsCZTAkbKJ
