### ISSUE TITLE
Steps not updating in the Nursery

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#7]
This is because the app doesn't have the functionality to tell the server to refresh their fitbit data.

Suggestion: add functionality to tell the server to refresh the Fitbit data (i.e., calling http://wellness.ccs.neu.edu/adc_dev/fitbit/update/person/{person_id}/

**Comment by estowell** [comment]
UI changes - 
Steps that app needs to do:
1. Send the user to fitbit
2. When the user goes back to the app, data should be downloaded from Fitbit
