### ISSUE TITLE
New challenges say "TextView"

### ISSUE THREAD

**Issue by breenmackenzie15** [WellnessLab/adc_caregiver#74]
![screenshot_20190228-114208](https://user-images.githubusercontent.com/46979152/53586491-4d342500-3b56-11e9-918e-d13dd8a45f28.png)
@hermansaksono

**Comment by takyyon** [comment]
![image](https://user-images.githubusercontent.com/11722204/54081967-62dae480-42e4-11e9-9099-be0343781932.png)

**Comment by hermansaksono** [comment]
I'm closing this as this is fixed in the next version. @breenmackenzie15 please review once you have the new version.
