### ISSUE TITLE
User's icons and profile should be shown in Community Garden and the user's Garden

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#78]

**Comment by xinylin360** [comment]
we need to be able to see other user's icons and profile pages from the community garden, once user visits someone else's garden, there's a profile icon on the top for that user, then user can  look at the other users profile by clicking on the icon, something like the images below:

![image](https://user-images.githubusercontent.com/46975347/53918333-b7583880-4034-11e9-8538-6d78e8c8e14a.png)

**Comment by hermansaksono** [comment]
This is addressed in PR 32
