### ISSUE TITLE
go&grow database need to have phone ID to send notifications. There should be "fmcToken" under userid (6)

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#81]

**Comment by hermansaksono** [comment]
@xinylin360, can you try to delete the app from your phone, install it again, and log in again to see if you can get the fcMToken? Thanks.

**Comment by xinylin360** [comment]
Just downloaded it again, I will need someone to like or reply to my messages first

**Comment by hermansaksono** [comment]
The bug is caused by the missing Google Play Services library on the test phone. I will close this issue and started issue #102.
