### ISSUE TITLE
The donut percentage for exercise log is showing incorect number

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#85]
if user logs 7 exercises in a challenge week, then its 100% on nursery page. If its greater than or equal to 100, a pop up comes up showing that the user can multiply the flower by 3 for the flower that week. This multiplied flower will show up when they plant the flower into the garden. So instead of planting that flower once, the user will plant the flower 3 times.

If did not acheive 100%, then users does not get multiplied flower.

**Comment by takyyon** [comment]
Fixed with Pull Request, https://github.ccs.neu.edu/Wellness/ADCaregiverApp/pull/31
