### ISSUE TITLE
7-day exercise graph for exercise logging is not correct

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#92]
The graph for 7-Day Excerise is supposed to show user’s number of exercise logged each day the user logs an exercise. 

Right now the situation is if I logged 3 exercise on Monday, that’s fine on the graph, but if I logged 4 exercises on Tuesday, the graph will automatically show I did 7 exercises on Tuesday, and for Monday it shows 0.

**Comment by hermansaksono** [comment]
Fixed in PR 37.
