### ISSUE TITLE
Spelling and Grammar Issues 

### ISSUE THREAD

**Issue by breenmackenzie15** [WellnessLab/adc_caregiver#97]
![image](https://user-images.githubusercontent.com/46979152/54286759-d564f200-457a-11e9-86a7-9ee7f5128a48.png)
![image](https://user-images.githubusercontent.com/46979152/54286775-dbf36980-457a-11e9-9750-454f8bc7913f.png)
![IMG_4192](https://user-images.githubusercontent.com/46979152/54286826-ee6da300-457a-11e9-90ae-5153c1e16c2a.jpg)
![IMG_4195](https://user-images.githubusercontent.com/46979152/54286837-f3325700-457a-11e9-80a9-21f5393d9763.jpg)
![IMG_4196](https://user-images.githubusercontent.com/46979152/54286844-f75e7480-457a-11e9-8a2d-e523ea15879c.jpg)

**Comment by hermansaksono** [comment]
Fix all of the above, except for the last one because that text also appeared in 6 instances. Therefore, I think, the source material was like that.
