### ISSUE TITLE
if user completed 0 goals for the challenge week, they will plant the seed in the garden

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#99]

**Comment by xinylin360** [comment]
this is the image of the seed, so if user completed 0 goals for the challenge week, they will plant this in the garden for any types of flower. 

https://drive.google.com/drive/u/2/folders/14nDHyDgMRvnWFPPjC0Hp03Z_Un_F2NDk

**Comment by hermansaksono** [comment]
Addressed in PR 44
